### ISSUE TITLE
Choice of theme for official website

### ISSUE THREAD

**Issue by Santara** [IndiaDeepLearningInitiative-IDLI/idli.github.io#1]
Hey guys,
Lets have a discussion regarding the __choice of theme__ for the official website of IDLI here. 
Please add new themes that we come across by editing @NeelShah18 's post.
Also post a comment with your top three choices in order.

**Comment by NeelShah18** [comment]
Theme option for IDLI:

1) http://bitwiser.in/bitwiser/demo.html
2) http://bloginn-jekyll.justgoodthemes.net/
3) https://panossakkos.github.io/personal-jekyll-theme/
4) https://luminousrubyist.github.io/airspace-jekyll/
5) http://himsel.me/
6) https://lenpaul.github.io/Lagrange/

**Comment by jrminz** [comment]
The themes are all great. So if I understand correctly you want to put this for poll on FB?

**Comment by Santara** [comment]
@jrminz I propose to discuss all the different alternatives that @NeelShah18 suggested here in this thread and narrow down to 3 choices for public opinion on Facebook.

**Comment by subratpanda** [comment]
+1 Anirban

**Comment by jrminz** [comment]
Guys in the SWAT (Static Website Action Team) Team, what are your specific preferences of the themes?

**Comment by NeelShah18** [comment]
My vote goes to 3rd and 5th.

**Comment by Santara** [comment]
@NeelShah18 Please give an ordered response. eg.:
#1:  3rd
#2: 5th

**Comment by NeelShah18** [comment]
#1: 5th
#2: 3rd

**Comment by jrminz** [comment]
#1: 6th
#2: 7th

So this is not like you can dynamically change themes as in some of the CMS,  right?

**Comment by NeelShah18** [comment]
yep @jrminz  right

**Comment by Santara** [comment]
#1: 6th
#2: 7th

**Comment by subratpanda** [comment]
#6
#7
#3

**Comment by Santara** [comment]
@malaikannan @biswatherockstar Waiting for your responses. :)

**Comment by malaikannan** [comment]
i like #4. that is most impressive one for me.

**Comment by Santara** [comment]
@IndiaDeepLearningInitiative-IDLI/swat You can modify your comments anytime... :) Lets set a deadline of 24 hours. I think we will find our desired theme tonight right here and wont have to go for a pubic poll. :P

**Comment by jrminz** [comment]
I like your idea @Santara. If there is a consensus within the team, there is no need to go for general polls. And that is what we should strive for.

**Comment by malaikannan** [comment]
we have 3 votes in number 1 for #6. Then lets go with it.

**Comment by jrminz** [comment]
I am a little bit sentimental about  one of the greatest mathematicians ever, Lagrange. Maybe that also played a part but agree that the theme has to be minimalist and scalable. But have to mention that #4 looks professional for a product.

**Comment by Santara** [comment]
I completely agree with @jrminz . If I had to make a startup, I would have chosen #4 unambiguously :) Never imagined such a beauty could be created in Jekyll... #6 looks academic enough to intrigue the university people and smart enough to pull the industry. :)

**Comment by NeelShah18** [comment]
I think LaGrange is good choice. because it is bootstrap enable too, so it will look good in mobile and tablet devices too.

**Comment by malaikannan** [comment]
@Santara may be that is the reason i gravitated towards it.

**Comment by Santara** [comment]
So guys, @IndiaDeepLearningInitiative-IDLI/swat We chose #6. https://lenpaul.github.io/Lagrange/ for our official website.
